[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
lib_extra_dirs = lib

build_flags =
    -Iinclude
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections